#!/usr/bin/env bash
# Generates a compat header that defines any OpenGL enum names the iOS
# OpenGL ES 3.0 SDK lacks, using the canonical values already listed in
# Irrlicht's generated mt_opengl.h.
set -euo pipefail
IRR="${1:?usage: gen_ios_gl_compat.sh <luanti/irr>}"
SRC="$IRR/include/mt_opengl.h"
OUT="$IRR/include/mt_ios_gl_compat.h"
{
  echo "// Generated by scripts/gen_ios_gl_compat.sh - do not edit."
  echo "// Fills in GL_* enums that the iOS OpenGLES ES3 SDK does not provide."
  echo "#pragma once"
  sed -nE 's/^[[:space:]]*static constexpr const [A-Za-z0-9_]+ ([A-Za-z0-9_]+) = ([^;]+);.*/\1 \2/p' "$SRC" \
  | awk '{ printf "#ifndef GL_%s\n#define GL_%s %s\n#endif\n", $1, $1, $2 }'
  cat <<'EXTRA'
// Extra enums referenced by Irrlicht that aren't in mt_opengl.h
#ifndef GL_FRAMEBUFFER_INCOMPLETE_FORMATS_EXT
#define GL_FRAMEBUFFER_INCOMPLETE_FORMATS_EXT 0x8CDA
#endif
#ifndef GL_FRAMEBUFFER_INCOMPLETE_DIMENSIONS_EXT
#define GL_FRAMEBUFFER_INCOMPLETE_DIMENSIONS_EXT 0x8CD9
#endif
EXTRA
} > "$OUT"
echo "wrote $OUT ($(grep -c '#define' "$OUT") defines)"
